name: React Release

permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - 'react-v*'

jobs:
  create-pypi-release:
    name: Create PyPI Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./torrent-downloader-react/backend
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: './torrent-downloader-react/backend/requirements.txt'
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './torrent-downloader-react/package-lock.json'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libtorrent-rasterbar-dev
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine wheel setuptools
          pip install -r requirements.txt
      
      - name: Install Node.js dependencies
        working-directory: ./torrent-downloader-react
        run: npm ci
      
      - name: Build package
        run: python build.py
      
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            torrent-downloader-react/backend/dist/*.whl
            torrent-downloader-react/backend/dist/*.tar.gz
          draft: false
          prerelease: false
          generate_release_notes: true
      
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN_REACT }}
        run: twine upload dist/*