name: Python Release

on:
  push:
    tags:
      - 'python-v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: torrent-downloader-python

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Publish package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN_PYTHON }}
      run: |
        python -m twine upload dist/* 